### ISSUE TITLE
Would you mind changing the logo of hypertrons organization?

### ISSUE THREAD

**Issue by tyn1998** [hypertrons/hypertrons-wonderland#4]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/32434520/160225240-218926dd-033f-43b4-b9b0-1b5c08ac6cc1.png">

I think that "bot" logo is better then this random logo.

**Comment by will-ww** [comment]
Sure~

**Comment by tyn1998** [comment]
Hi @frank-zsy, could you add a logo for this organization?

**Comment by frank-zsy** [comment]
Done.

**Comment by tyn1998** [comment]
The logo looks great, thanks!
